version: "3.8"

volumes:
  certs:
    driver: local
  esdata01:
    driver: local
  kibanadata:
    driver: local
  metricbeatdata01:
    driver: local
  filebeatdata01:
    driver: local
  logstashdata01:
    driver: local

networks:
  default:
    name: elastic
    external: false

services:
  rabbitmq:
    extends:
      file: templates/rabbitmq.yml
      service: rabbitmq
  
  elasticsearch-setup:
    extends:
      file: templates/elasticsearch.yml
      service: elasticsearch-setup
  
  es01:
    extends:
      file: templates/elasticsearch.yml
      service: es01
  
  kibana:
    extends:
      file: templates/elasticsearch.yml
      service: kibana

  metricbeat01:
    extends:
      file: templates/elasticsearch.yml
      service: metricbeat01
  
  filebeat01:
    extends:
      file: templates/elasticsearch.yml
      service: filebeat01

  logstash01:
    extends:
      file: templates/elasticsearch.yml
      service: logstash01
