version: "3.8"
services:
  rabbitmq:
    extends:
      file: templates/rabbitmq.yml
      service: rabbitmq
  
  message-publisher-api:
    extends:
      file: templates/api.yml
      service: message-publisher-api
    environment:
      MESSAGEBUS_HOSTNAME: rabbitmq
