//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageBus.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MessageBus.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBus inserted into cache for queue {0}..
        /// </summary>
        internal static string ChannelPool_MessageBus_Insertion {
            get {
                return ResourceManager.GetString("ChannelPool_MessageBus_Insertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBus retrieved from cache to queue {0}..
        /// </summary>
        internal static string ChannelPool_MessageBus_Retrieved {
            get {
                return ResourceManager.GetString("ChannelPool_MessageBus_Retrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBus connection attempt number {0}..
        /// </summary>
        internal static string MessageBus_Connection_Attempt {
            get {
                return ResourceManager.GetString("MessageBus_Connection_Attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to MessageBus: Details: {0}..
        /// </summary>
        internal static string MessageBus_Connection_Error {
            get {
                return ResourceManager.GetString("MessageBus_Connection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to MessageBus was lost..
        /// </summary>
        internal static string MessageBus_Connection_Lost {
            get {
                return ResourceManager.GetString("MessageBus_Connection_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to MessageBus completed successfully..
        /// </summary>
        internal static string MessageBus_Connection_With_Success {
            get {
                return ResourceManager.GetString("MessageBus_Connection_With_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating the MessageBus Model. Details: {0}..
        /// </summary>
        internal static string Model_Created_With_Error {
            get {
                return ResourceManager.GetString("Model_Created_With_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBus Model successfully created..
        /// </summary>
        internal static string Model_Created_With_Success {
            get {
                return ResourceManager.GetString("Model_Created_With_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing message to queue {0}..
        /// </summary>
        internal static string Publishing_To_Queue {
            get {
                return ResourceManager.GetString("Publishing_To_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error publishing message to queue {0}. Details: {1}.
        /// </summary>
        internal static string Publishing_To_Queue_With_Error {
            get {
                return ResourceManager.GetString("Publishing_To_Queue_With_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to queue {0}. Details: {1}..
        /// </summary>
        internal static string Queue_Connection_With_Error {
            get {
                return ResourceManager.GetString("Queue_Connection_With_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successfully made to queue {0}..
        /// </summary>
        internal static string Queue_Connection_With_Success {
            get {
                return ResourceManager.GetString("Queue_Connection_With_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RabbitMQ hostname was not provided in the environment variables, see the project README..
        /// </summary>
        internal static string Validator_Options_Hostname {
            get {
                return ResourceManager.GetString("Validator_Options_Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RabbitMQ password was not provided in the environment variables, see the project README..
        /// </summary>
        internal static string Validator_Options_Password {
            get {
                return ResourceManager.GetString("Validator_Options_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RabbitMQ username was not provided in the environment variables, see the project README..
        /// </summary>
        internal static string Validator_Options_Username {
            get {
                return ResourceManager.GetString("Validator_Options_Username", resourceCulture);
            }
        }
    }
}
