version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.11.23-management
    container_name: rabbitmq
    ports:
      - 61613:61613
      - 5671:5671
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
